Adds new edition fields
psu-libraries/psulib_traject pull request #250
Opened 2020-09-30 13:07 UTC by cdmo

2020-09-30 19:07 UTC, banukutlu commented on lib/traject/psulib_config.rb
> +to_field 'other_edition_ssm', extract_marc('775|0*|iabcdefghikmnor')
```suggestion
to_field 'other_edition_ssm', extract_marc('775|0*|iabcdefghkmnor')
```

2020-10-01 02:22 UTC, banukutlu requested changes
looks good, just one change needed for the extra i

2020-10-01 02:28 UTC, cdmo commented on lib/traject/psulib_config.rb
> +to_field 'other_edition_ssm', extract_marc('775|0*|iabcdefghikmnor')
👌 nice catch

2020-10-01 02:42 UTC, banukutlu approved these changes
✔️

2020-10-01 02:43 UTC, merged